create table if not exists fenghuo_ad_group
(
    id                bigint                               not null
        primary key,
    profile_id        varchar(64)                          not null comment '关联的市场店铺Id',
    ad_group_id       varchar(64)                          null comment '活动组ID',
    campaign_id       varchar(64)                          null comment '亚马逊Id',
    name              varchar(64)                          null comment '名称',
    state             varchar(32)                          null comment 'The state of the campaign. e.g.,enabled, paused, archived',
    default_bid       decimal(20, 4)                       null,
    serving_status    varchar(64)                          null comment 'The status of the campaign.e.g.,[ ADVERTISER_STATUS_ENABLED, STATUS_UNAVAILABLE, ADVERTISER_PAUSED, ACCOUNT_OUT_OF_BUDGET, ADVERTISER_PAYMENT_FAILURE, CAMPAIGN_PAUSED, CAMPAIGN_ARCHIVED, PENDING_START_DATE, ENDED, CAMPAIGN_OUT_OF_BUDGET ]',
    creation_date     bigint                               null comment 'Epoch date the campaign was created.',
    last_updated_date bigint                               null comment 'Epoch date of the last update to any property associated with the campaign in Amazon',
    creator           varchar(20)                          null,
    modifier          varchar(20)                          null,
    deleted           tinyint(1) default 0                 null,
    enabled           tinyint(1) default 1                 null,
    gmt_create        datetime   default CURRENT_TIMESTAMP not null comment '创建时间',
    gmt_modified      datetime   default CURRENT_TIMESTAMP not null on update CURRENT_TIMESTAMP comment '修改时间',
    constraint uk_ad_group_id
        unique (ad_group_id)
)
    comment '活动组';

create index idx_group_profile
    on fenghuo_ad_group (campaign_id, profile_id);

create index idx_profile_group
    on fenghuo_ad_group (profile_id, ad_group_id, campaign_id);

create table if not exists fenghuo_ad_strategy
(
    id                    bigint               not null
        primary key,
    enabled               tinyint(1) default 0 null,
    deleted               tinyint(1) default 0 null,
    gmt_create            datetime(3)          null,
    gmt_modified          datetime(3)          null,
    creator               varchar(20)          null,
    modifier              varchar(20)          null,
    tenant_id             varchar(20)          not null,
    type                  varchar(20)          not null,
    original_value        decimal(18, 6)       null,
    profile_id            varchar(20)          null,
    campaign_id           varchar(20)          null,
    timezone              varchar(20)          null,
    last_check_start_time bigint               null,
    last_check_end_time   bigint               null,
    last_proc_status      int                  null,
    rule                  varchar(20)          null,
    delta_value           decimal(18, 6)       null,
    max_value             decimal(18, 6)       null,
    rule_details          varchar(1000)        null,
    used_type             varchar(30)          not null,
    used_entity_id        varchar(20)          not null,
    active_type           varchar(20)          not null,
    constraint unik_key
        unique (type, used_type, used_entity_id, tenant_id)
)
    charset = utf8;

create index idx_type_enabled
    on fenghuo_ad_strategy (type, enabled, last_proc_status, last_check_end_time);

create table if not exists fenghuo_campaign
(
    id                     bigint                               not null
        primary key,
    profile_id             varchar(64)                          not null comment '关联的市场店铺Id',
    campaign_id            varchar(64)                          null comment '亚马逊Id',
    name                   varchar(128)                         null comment '名称',
    start_date             varchar(32)                          null comment '活动开始时间， 如：20190101',
    end_date               varchar(32)                          null comment '活动结束时间， 如：20190101',
    state                  varchar(32)                          null comment 'The state of the campaign. e.g.,enabled, paused, archived',
    portfolio_id           varchar(64)                          null comment '广告组合id',
    campaign_type          varchar(32)                          null comment 'The advertising product managed by this campaign.',
    targeting_type         varchar(32)                          null comment 'The type of targeting of the campaign.Enum: manul,auto',
    daily_budget           decimal(20, 4)                       null,
    premium_bid_adjustment tinyint(1)                           null comment '是否溢价调整',
    bidding                json                                 null comment 'json结构的对广告位的竞价调整配置',
    tags                   json                                 null,
    serving_status         varchar(64)                          null comment 'The status of the campaign.e.g.,[ ADVERTISER_STATUS_ENABLED, STATUS_UNAVAILABLE, ADVERTISER_PAUSED, ACCOUNT_OUT_OF_BUDGET, ADVERTISER_PAYMENT_FAILURE, CAMPAIGN_PAUSED, CAMPAIGN_ARCHIVED, PENDING_START_DATE, ENDED, CAMPAIGN_OUT_OF_BUDGET ]',
    creation_date          bigint                               null comment 'Epoch date the campaign was created.',
    last_updated_date      bigint                               null comment 'Epoch date of the last update to any property associated with the campaign in Amazon',
    creator                varchar(20)                          null,
    modifier               varchar(20)                          null,
    deleted                tinyint(1) default 0                 null,
    enabled                tinyint(1) default 1                 null,
    gmt_create             datetime   default CURRENT_TIMESTAMP not null comment '创建时间',
    gmt_modified           datetime   default CURRENT_TIMESTAMP not null on update CURRENT_TIMESTAMP comment '修改时间',
    constraint uk_campaignid
        unique (campaign_id)
)
    comment ' 活动 ';

create index idx_profile_campaign
    on fenghuo_campaign (profile_id, campaign_id);

create table if not exists fenghuo_effect_ad_group
(
    id                        bigint auto_increment
        primary key,
    platform_name             varchar(100)   null comment '平台名称',
    platform_id               varchar(100)   null comment '平台id',
    market_place_name         varchar(100)   null comment '站点',
    market_place_code         varchar(100)   null comment '站点编码',
    first_center_name         varchar(100)   null comment '销售一级事业部名称',
    first_center_code         varchar(100)   null comment '销售一级事业部编码',
    second_center_name        varchar(100)   null comment '销售二级事业部名称',
    second_center_code        varchar(100)   null comment '销售二级事业部编码',
    store_manager             varchar(100)   null comment '店铺负责人',
    store_name                varchar(100)   null comment '店铺名称',
    store_id                  varchar(100)   null comment '店铺id',
    bc_id                     varchar(100)   null comment 'bc_id',
    timezone                  varchar(100)   null comment '时区',
    advertising_type          varchar(100)   null comment '广告类型',
    ad_mode                   varchar(100)   null comment '广告模式',
    campaign_bidding_strategy varchar(100)   null comment '广告活动竞价策略',
    portfolio_id              varchar(100)   null comment '广告组合id',
    portfolio_name            varchar(100)   null comment '广告组合名称',
    campaign_name             varchar(300)   null comment '广告活动名称',
    campaign_id               varchar(100)   null comment '广告活动id',
    campaign_status           varchar(100)   null comment '广告活动最新状态',
    currency_code             varchar(100)   null comment '币种',
    campaign_create_date      datetime       null comment '广告活动创建时间',
    campaign_end_date         datetime       null comment '广告活动结束时间',
    ad_group_name             varchar(300)   null comment '广告组名称',
    ad_group_id               varchar(100)   null comment '广告组id',
    ad_group_create_date      varchar(100)   null comment '广告组创建时间',
    ad_group_end_date         varchar(100)   null comment '广告组结束时间',
    ad_group_status           varchar(100)   null comment '广告组状态',
    asin_cnt                  bigint         null comment 'asin数量',
    sku_cnt                   bigint         null comment 'sku数量',
    goods_cnt                 bigint         null comment 'goods数量',
    impressions               bigint         null comment '曝光量',
    clicks                    bigint         null comment '点击量',
    order_quantiy             bigint         null comment '广告销售量',
    sale_amt                  decimal(18, 6) null comment '广告销售额',
    cpc                       decimal(18, 6) null comment '单个点击成本',
    acos                      decimal(18, 6) null comment '成本收入占比',
    roas                      decimal(18, 6) null comment '投入产出比',
    ctr                       decimal(18, 6) null comment '点击率',
    cvr                       decimal(18, 6) null comment '转化率',
    target_cnt                bigint         null comment '定位总数',
    data_dt                   varchar(100)   null,
    etl_data_dt               varchar(100)   null,
    update_data_dt            varchar(100)   null,
    cost                      decimal(18, 6) null comment '广告花费',
    user_id                   varchar(100)   null comment '租户id',
    user_name                 varchar(100)   null comment '租户名称',
    place_is                  decimal(18, 6) null,
    vcpm                      decimal(18, 6) null,
    campaign_budget_basic_amt decimal(18, 6) null,
    campaign_budget_amt       decimal(18, 6) null,
    campaign_budget_status    decimal(18, 6) null,
    constraint idx_ad_group_unique
        unique (ad_group_id, market_place_code, advertising_type, store_id, campaign_id)
)
    comment '广告组效果统计' charset = utf8;

create table if not exists fenghuo_effect_campaign
(
    id                        bigint auto_increment
        primary key,
    market_place_name         varchar(100)   null comment '站点',
    market_place_code         varchar(100)   null comment '站点编码',
    first_center_name         varchar(100)   null comment '销售一级事业部名称',
    first_center_code         varchar(100)   null comment '销售一级事业部编码',
    second_center_name        varchar(100)   null comment '销售二级事业部名称',
    second_center_code        varchar(100)   null comment '销售二级事业部编码',
    store_manager             varchar(100)   null comment '店铺负责人',
    store_name                varchar(100)   null comment '店铺名称',
    store_id                  varchar(100)   null comment '店铺id',
    bc_id                     varchar(100)   null comment 'bc_id',
    advertising_type          varchar(100)   null comment '广告类型',
    portfolio_id              varchar(100)   null comment '广告组合id',
    portfolio_name            varchar(300)   null comment '广告组合名称',
    campaign_name             varchar(300)   null comment '广告活动名称',
    campaign_id               varchar(100)   null comment '广告活动id',
    campaign_status           varchar(100)   null comment '广告活动最新状态',
    currency_code             varchar(100)   null comment '币种',
    campaign_create_date      datetime       null comment '广告活动创建时间',
    campaign_end_date         datetime       null comment '广告活动结束时间',
    asin_cnt                  bigint         null comment 'asin数量',
    sku_cnt                   bigint         null comment 'sku数量',
    goods_cnt                 bigint         null comment 'goods数量',
    ad_group_cnt              bigint         null comment '广告组数量',
    impressions               bigint         null comment '曝光量',
    clicks                    bigint         null comment '点击量',
    order_quantiy             bigint         null comment '广告销售量',
    sale_amt                  decimal(18, 6) null comment '广告销售额',
    cpc                       decimal(18, 6) null comment '单个点击成本',
    acos                      decimal(18, 6) null comment '成本收入占比',
    roas                      decimal(18, 6) null comment '投入产出比',
    ctr                       decimal(18, 6) null comment '点击率',
    cvr                       decimal(18, 6) null comment '转化率',
    target_cnt                bigint         null comment '定位总数',
    data_dt                   varchar(100)   null,
    etl_data_dt               varchar(100)   null,
    update_data_dt            varchar(100)   null,
    platform_name             varchar(100)   null comment '平台名称',
    platform_id               varchar(100)   null comment '平台id',
    timezone                  varchar(100)   null comment '时区',
    ad_mode                   varchar(100)   null comment '广告模式',
    campaign_bidding_strategy varchar(100)   null comment '广告活动竞价策略',
    cost                      decimal(18, 6) null comment '广告花费',
    user_id                   varchar(100)   null comment '租户id',
    user_name                 varchar(100)   null comment '租户名称',
    place_is                  decimal(18, 6) null,
    vcpm                      decimal(18, 6) null,
    campaign_budget_basic_amt decimal(18, 6) null,
    campaign_budget_amt       decimal(18, 6) null,
    campaign_budget_status    decimal(18, 6) null,
    constraint idx_campaign_unique
        unique (campaign_id, market_place_code, advertising_type, store_id)
)
    comment '广告活动效果统计' charset = utf8;

create table if not exists fenghuo_effect_keywords
(
    id                bigint auto_increment
        primary key,
    keyword_text      varchar(100)   null,
    campaign_status   varchar(100)   null,
    impressions       bigint         null,
    clicks            bigint         null,
    cost              decimal(18, 6) null,
    order_quantity    bigint         null,
    sale_amt          decimal(18, 6) null,
    ctr               decimal(18, 6) null,
    cvr               decimal(18, 6) null,
    cpc               decimal(18, 6) null,
    keyword_rank      bigint         null,
    data_dt           varchar(100)   null,
    etl_data_dt       datetime       null,
    update_data_dt    datetime       null,
    market_place_code varchar(64)    null,
    market_place_name varchar(64)    null,
    constraint idx_keyword_text
        unique (keyword_text),
    constraint market_place_code
        unique (market_place_code, keyword_text),
    constraint market_place_name
        unique (market_place_name, keyword_text)
)
    comment '子不语asin-关键词的效果统计表(最近30天滚动统计)' charset = utf8;

create table if not exists fenghuo_effect_mkt_adv_sku_03
(
    id                            bigint auto_increment
        primary key,
    profile_id                    varchar(100)   null comment '广告配置id',
    portfolio_id                  varchar(100)   null comment '广告组合id',
    portfolio_name                varchar(100)   null comment '广告组合名称',
    campaign_id                   varchar(100)   null comment '广告活动id',
    campaign_name                 varchar(100)   null comment '广告活动名称',
    ad_group_id                   varchar(100)   null comment '广告组id',
    ad_group_name                 varchar(100)   null comment '广告组名称',
    ad_id                         varchar(100)   null comment '广告id',
    timezone                      varchar(100)   null comment '时区',
    currency_code                 varchar(100)   null comment '货币编码',
    campaign_status               varchar(100)   null comment '广告活动状态',
    ad_group_status               varchar(100)   null comment '广告组状态',
    advertising_type              varchar(100)   null comment '广告类型',
    ad_mode                       varchar(100)   null comment '广告投放模式：自动手动',
    campaign_bidding_strategy     varchar(100)   null comment '竞价策略：固定动态',
    target_keyword                varchar(100)   null comment '关键词还是商品投放',
    bid_plus                      bigint         null comment '竞价溢价',
    campaign_budget_amt           varchar(100)   null comment '广告活动预算金额',
    campaign_budget_type          varchar(100)   null comment '广告活动预算类型',
    campaign_rule_budget_amt      varchar(100)   null comment '广告活动规则基本预算金额',
    campaign_rule_budget_id       varchar(100)   null comment '广告活动规则基本预算id',
    campaign_budget_rule_name     varchar(100)   null comment '广告活动预算规则名称',
    campaign_budget_currency_code varchar(100)   null comment '广告活动预算币种',
    place                         varchar(100)   null comment '广告位',
    sn_code                       varchar(100)   null comment 'sn_code',
    seller_sku                    varchar(100)   null comment '广告推广的子不语sku',
    sku_name                      varchar(100)   null comment 'sku名称',
    asin                          varchar(100)   null comment '推广的Asin',
    parent_asin                   varchar(100)   null comment 'parent_asin',
    item_name                     varchar(300)   null comment 'listing',
    price                         decimal(18, 6) null comment '页面价格',
    goods_code                    varchar(100)   null comment '货号编码',
    goods_id                      bigint         null comment 'goods_id',
    goods_name                    varchar(100)   null comment '货号名称',
    goods_type                    bigint         null comment '商品类型',
    goods_size                    varchar(100)   null comment '商品尺寸',
    goods_color                   varchar(100)   null comment '颜色',
    fit_season_name               varchar(100)   null comment '适销季节',
    category_one_id               varchar(100)   null comment '一级类目id',
    category_one_name             varchar(100)   null comment '一级类目名称',
    category_two_id               varchar(100)   null comment '二级类目id',
    category_two_name             varchar(100)   null comment '二级类目名称',
    category_three_id             varchar(100)   null comment '三级类目id',
    category_three_name           varchar(100)   null comment '三级类目名称',
    category_four_id              varchar(100)   null comment '四级类目id',
    category_four_name            varchar(100)   null comment '四级类目名称',
    category_five_id              varchar(100)   null comment '五级类目id',
    category_five_name            varchar(100)   null comment '五级类目名称',
    category_six_id               varchar(100)   null comment '六级类目id',
    category_six_name             varchar(100)   null comment '六级类目名称',
    store_id                      bigint         null comment '店铺id',
    market_place_code             varchar(100)   null comment '站点编码',
    market_place_name             varchar(100)   null comment '站点',
    platform_id                   varchar(100)   null comment '平台id',
    platform_name                 varchar(100)   null comment '平台名称',
    main_img_url                  varchar(300)   null comment '主图goods_code粒度',
    main_asin_url                 varchar(200)   null comment '主卖链接',
    business_center_id            bigint         null comment '商品事业部id',
    business_center_code          varchar(100)   null comment '商品事业部code',
    business_center_name          varchar(100)   null comment '商品事业部名称',
    first_center_code             varchar(100)   null comment '一级销售事业部编码',
    first_center_name             varchar(100)   null comment '一级销售事业部名称',
    second_center_code            varchar(100)   null comment '二级事业部编码',
    second_center_name            varchar(100)   null comment '二级事业部名称',
    store_name                    varchar(100)   null comment '店铺名名称',
    store_manager                 varchar(100)   null comment '店铺负责人',
    performance_one_id            varchar(100)   null comment '业绩归属人id',
    performance_one_name          varchar(100)   null comment '业绩归属人名称',
    impressions                   bigint         null comment '曝光量',
    clicks                        bigint         null comment '点击量',
    order_quantity                bigint         null comment '归因销售量',
    order_quantity_curr_year      bigint         null comment '当年的总销售量',
    order_quantity_total_year     bigint         null comment '历史累计总销售量',
    order_quantity_7d             bigint         null comment '最近7天销售量',
    order_quantity_1d             bigint         null comment '最近1天的销售量',
    sale_pct                      decimal(18, 6) null comment '售罄率',
    quantity_same_sku             bigint         null comment '本sku的归因广告销售量',
    quantity_same_sku_1d          bigint         null comment '本sku的归因1天广告销售量',
    exchange_rate                 decimal(18, 6) null comment '管理汇率',
    sale_amt                      decimal(18, 6) null comment '总的归因广告销售量',
    sale_amt_1d                   decimal(18, 6) null comment '总的1天归因广告销售量',
    tol_sale_amt                  decimal(18, 6) null comment '总销售金额',
    tol_order_quantity            bigint         null comment '总销售量',
    cost                          decimal(18, 6) null comment '广告花费',
    same_sku_amt                  decimal(18, 6) null comment '本sku归因广告销售金额',
    same_sku_amt_1d               decimal(18, 6) null comment '本sku的1天归因广告销售金额',
    data_dt                       varchar(100)   null comment '数据日期',
    report_date                   datetime       null comment '广告报告时间',
    first_purchase_date           datetime       null comment '首次售卖时间',
    campaign_create_date          datetime       null comment '广告活动创建时间',
    campaign_end_date             datetime       null comment '广告活动停止时间',
    ad_group_create_date          datetime       null comment '广告组创建时间',
    ad_group_end_date             datetime       null comment '广告组停止时间',
    etl_data_dt                   datetime       null comment '数据加载日期',
    update_data_dt                datetime       null comment '数据更新日期',
    report_date_str               varchar(10)    null comment '广告报告时间-字符串',
    constraint idx_adv_sku_unique
        unique (report_date, advertising_type, market_place_code, store_id, campaign_id, ad_group_id, goods_code,
                seller_sku)
)
    comment 'sku粒度广告投放表-report_date_str%10==3' charset = utf8;

create table if not exists fenghuo_effect_mkt_adv_sku_04
(
    id                            bigint auto_increment
        primary key,
    profile_id                    varchar(100)   null comment '广告配置id',
    portfolio_id                  varchar(100)   null comment '广告组合id',
    portfolio_name                varchar(100)   null comment '广告组合名称',
    campaign_id                   varchar(100)   null comment '广告活动id',
    campaign_name                 varchar(100)   null comment '广告活动名称',
    ad_group_id                   varchar(100)   null comment '广告组id',
    ad_group_name                 varchar(100)   null comment '广告组名称',
    ad_id                         varchar(100)   null comment '广告id',
    timezone                      varchar(100)   null comment '时区',
    currency_code                 varchar(100)   null comment '货币编码',
    campaign_status               varchar(100)   null comment '广告活动状态',
    ad_group_status               varchar(100)   null comment '广告组状态',
    advertising_type              varchar(100)   null comment '广告类型',
    ad_mode                       varchar(100)   null comment '广告投放模式：自动手动',
    campaign_bidding_strategy     varchar(100)   null comment '竞价策略：固定动态',
    target_keyword                varchar(100)   null comment '关键词还是商品投放',
    bid_plus                      bigint         null comment '竞价溢价',
    campaign_budget_amt           varchar(100)   null comment '广告活动预算金额',
    campaign_budget_type          varchar(100)   null comment '广告活动预算类型',
    campaign_rule_budget_amt      varchar(100)   null comment '广告活动规则基本预算金额',
    campaign_rule_budget_id       varchar(100)   null comment '广告活动规则基本预算id',
    campaign_budget_rule_name     varchar(100)   null comment '广告活动预算规则名称',
    campaign_budget_currency_code varchar(100)   null comment '广告活动预算币种',
    place                         varchar(100)   null comment '广告位',
    sn_code                       varchar(100)   null comment 'sn_code',
    seller_sku                    varchar(100)   null comment '广告推广的子不语sku',
    sku_name                      varchar(100)   null comment 'sku名称',
    asin                          varchar(100)   null comment '推广的Asin',
    parent_asin                   varchar(100)   null comment 'parent_asin',
    item_name                     varchar(300)   null comment 'listing',
    price                         decimal(18, 6) null comment '页面价格',
    goods_code                    varchar(100)   null comment '货号编码',
    goods_id                      bigint         null comment 'goods_id',
    goods_name                    varchar(100)   null comment '货号名称',
    goods_type                    bigint         null comment '商品类型',
    goods_size                    varchar(100)   null comment '商品尺寸',
    goods_color                   varchar(100)   null comment '颜色',
    fit_season_name               varchar(100)   null comment '适销季节',
    category_one_id               varchar(100)   null comment '一级类目id',
    category_one_name             varchar(100)   null comment '一级类目名称',
    category_two_id               varchar(100)   null comment '二级类目id',
    category_two_name             varchar(100)   null comment '二级类目名称',
    category_three_id             varchar(100)   null comment '三级类目id',
    category_three_name           varchar(100)   null comment '三级类目名称',
    category_four_id              varchar(100)   null comment '四级类目id',
    category_four_name            varchar(100)   null comment '四级类目名称',
    category_five_id              varchar(100)   null comment '五级类目id',
    category_five_name            varchar(100)   null comment '五级类目名称',
    category_six_id               varchar(100)   null comment '六级类目id',
    category_six_name             varchar(100)   null comment '六级类目名称',
    store_id                      bigint         null comment '店铺id',
    market_place_code             varchar(100)   null comment '站点编码',
    market_place_name             varchar(100)   null comment '站点',
    platform_id                   varchar(100)   null comment '平台id',
    platform_name                 varchar(100)   null comment '平台名称',
    main_img_url                  varchar(300)   null comment '主图goods_code粒度',
    main_asin_url                 varchar(200)   null comment '主卖链接',
    business_center_id            bigint         null comment '商品事业部id',
    business_center_code          varchar(100)   null comment '商品事业部code',
    business_center_name          varchar(100)   null comment '商品事业部名称',
    first_center_code             varchar(100)   null comment '一级销售事业部编码',
    first_center_name             varchar(100)   null comment '一级销售事业部名称',
    second_center_code            varchar(100)   null comment '二级事业部编码',
    second_center_name            varchar(100)   null comment '二级事业部名称',
    store_name                    varchar(100)   null comment '店铺名名称',
    store_manager                 varchar(100)   null comment '店铺负责人',
    performance_one_id            varchar(100)   null comment '业绩归属人id',
    performance_one_name          varchar(100)   null comment '业绩归属人名称',
    impressions                   bigint         null comment '曝光量',
    clicks                        bigint         null comment '点击量',
    order_quantity                bigint         null comment '归因销售量',
    order_quantity_curr_year      bigint         null comment '当年的总销售量',
    order_quantity_total_year     bigint         null comment '历史累计总销售量',
    order_quantity_7d             bigint         null comment '最近7天销售量',
    order_quantity_1d             bigint         null comment '最近1天的销售量',
    sale_pct                      decimal(18, 6) null comment '售罄率',
    quantity_same_sku             bigint         null comment '本sku的归因广告销售量',
    quantity_same_sku_1d          bigint         null comment '本sku的归因1天广告销售量',
    exchange_rate                 decimal(18, 6) null comment '管理汇率',
    sale_amt                      decimal(18, 6) null comment '总的归因广告销售量',
    sale_amt_1d                   decimal(18, 6) null comment '总的1天归因广告销售量',
    tol_sale_amt                  decimal(18, 6) null comment '总销售金额',
    tol_order_quantity            bigint         null comment '总销售量',
    cost                          decimal(18, 6) null comment '广告花费',
    same_sku_amt                  decimal(18, 6) null comment '本sku归因广告销售金额',
    same_sku_amt_1d               decimal(18, 6) null comment '本sku的1天归因广告销售金额',
    data_dt                       varchar(100)   null comment '数据日期',
    report_date                   datetime       null comment '广告报告时间',
    first_purchase_date           datetime       null comment '首次售卖时间',
    campaign_create_date          datetime       null comment '广告活动创建时间',
    campaign_end_date             datetime       null comment '广告活动停止时间',
    ad_group_create_date          datetime       null comment '广告组创建时间',
    ad_group_end_date             datetime       null comment '广告组停止时间',
    etl_data_dt                   datetime       null comment '数据加载日期',
    update_data_dt                datetime       null comment '数据更新日期',
    report_date_str               varchar(10)    null comment '广告报告时间-字符串',
    constraint idx_adv_sku_unique
        unique (report_date, advertising_type, market_place_code, store_id, campaign_id, ad_group_id, goods_code,
                seller_sku)
)
    comment 'sku粒度广告投放表-report_date_str%10==4' charset = utf8;

create table if not exists fenghuo_effect_mkt_adv_sku_05
(
    id                            bigint auto_increment
        primary key,
    profile_id                    varchar(100)   null comment '广告配置id',
    portfolio_id                  varchar(100)   null comment '广告组合id',
    portfolio_name                varchar(100)   null comment '广告组合名称',
    campaign_id                   varchar(100)   null comment '广告活动id',
    campaign_name                 varchar(100)   null comment '广告活动名称',
    ad_group_id                   varchar(100)   null comment '广告组id',
    ad_group_name                 varchar(100)   null comment '广告组名称',
    ad_id                         varchar(100)   null comment '广告id',
    timezone                      varchar(100)   null comment '时区',
    currency_code                 varchar(100)   null comment '货币编码',
    campaign_status               varchar(100)   null comment '广告活动状态',
    ad_group_status               varchar(100)   null comment '广告组状态',
    advertising_type              varchar(100)   null comment '广告类型',
    ad_mode                       varchar(100)   null comment '广告投放模式：自动手动',
    campaign_bidding_strategy     varchar(100)   null comment '竞价策略：固定动态',
    target_keyword                varchar(100)   null comment '关键词还是商品投放',
    bid_plus                      bigint         null comment '竞价溢价',
    campaign_budget_amt           varchar(100)   null comment '广告活动预算金额',
    campaign_budget_type          varchar(100)   null comment '广告活动预算类型',
    campaign_rule_budget_amt      varchar(100)   null comment '广告活动规则基本预算金额',
    campaign_rule_budget_id       varchar(100)   null comment '广告活动规则基本预算id',
    campaign_budget_rule_name     varchar(100)   null comment '广告活动预算规则名称',
    campaign_budget_currency_code varchar(100)   null comment '广告活动预算币种',
    place                         varchar(100)   null comment '广告位',
    sn_code                       varchar(100)   null comment 'sn_code',
    seller_sku                    varchar(100)   null comment '广告推广的子不语sku',
    sku_name                      varchar(100)   null comment 'sku名称',
    asin                          varchar(100)   null comment '推广的Asin',
    parent_asin                   varchar(100)   null comment 'parent_asin',
    item_name                     varchar(300)   null comment 'listing',
    price                         decimal(18, 6) null comment '页面价格',
    goods_code                    varchar(100)   null comment '货号编码',
    goods_id                      bigint         null comment 'goods_id',
    goods_name                    varchar(100)   null comment '货号名称',
    goods_type                    bigint         null comment '商品类型',
    goods_size                    varchar(100)   null comment '商品尺寸',
    goods_color                   varchar(100)   null comment '颜色',
    fit_season_name               varchar(100)   null comment '适销季节',
    category_one_id               varchar(100)   null comment '一级类目id',
    category_one_name             varchar(100)   null comment '一级类目名称',
    category_two_id               varchar(100)   null comment '二级类目id',
    category_two_name             varchar(100)   null comment '二级类目名称',
    category_three_id             varchar(100)   null comment '三级类目id',
    category_three_name           varchar(100)   null comment '三级类目名称',
    category_four_id              varchar(100)   null comment '四级类目id',
    category_four_name            varchar(100)   null comment '四级类目名称',
    category_five_id              varchar(100)   null comment '五级类目id',
    category_five_name            varchar(100)   null comment '五级类目名称',
    category_six_id               varchar(100)   null comment '六级类目id',
    category_six_name             varchar(100)   null comment '六级类目名称',
    store_id                      bigint         null comment '店铺id',
    market_place_code             varchar(100)   null comment '站点编码',
    market_place_name             varchar(100)   null comment '站点',
    platform_id                   varchar(100)   null comment '平台id',
    platform_name                 varchar(100)   null comment '平台名称',
    main_img_url                  varchar(300)   null comment '主图goods_code粒度',
    main_asin_url                 varchar(200)   null comment '主卖链接',
    business_center_id            bigint         null comment '商品事业部id',
    business_center_code          varchar(100)   null comment '商品事业部code',
    business_center_name          varchar(100)   null comment '商品事业部名称',
    first_center_code             varchar(100)   null comment '一级销售事业部编码',
    first_center_name             varchar(100)   null comment '一级销售事业部名称',
    second_center_code            varchar(100)   null comment '二级事业部编码',
    second_center_name            varchar(100)   null comment '二级事业部名称',
    store_name                    varchar(100)   null comment '店铺名名称',
    store_manager                 varchar(100)   null comment '店铺负责人',
    performance_one_id            varchar(100)   null comment '业绩归属人id',
    performance_one_name          varchar(100)   null comment '业绩归属人名称',
    impressions                   bigint         null comment '曝光量',
    clicks                        bigint         null comment '点击量',
    order_quantity                bigint         null comment '归因销售量',
    order_quantity_curr_year      bigint         null comment '当年的总销售量',
    order_quantity_total_year     bigint         null comment '历史累计总销售量',
    order_quantity_7d             bigint         null comment '最近7天销售量',
    order_quantity_1d             bigint         null comment '最近1天的销售量',
    sale_pct                      decimal(18, 6) null comment '售罄率',
    quantity_same_sku             bigint         null comment '本sku的归因广告销售量',
    quantity_same_sku_1d          bigint         null comment '本sku的归因1天广告销售量',
    exchange_rate                 decimal(18, 6) null comment '管理汇率',
    sale_amt                      decimal(18, 6) null comment '总的归因广告销售量',
    sale_amt_1d                   decimal(18, 6) null comment '总的1天归因广告销售量',
    tol_sale_amt                  decimal(18, 6) null comment '总销售金额',
    tol_order_quantity            bigint         null comment '总销售量',
    cost                          decimal(18, 6) null comment '广告花费',
    same_sku_amt                  decimal(18, 6) null comment '本sku归因广告销售金额',
    same_sku_amt_1d               decimal(18, 6) null comment '本sku的1天归因广告销售金额',
    data_dt                       varchar(100)   null comment '数据日期',
    report_date                   datetime       null comment '广告报告时间',
    first_purchase_date           datetime       null comment '首次售卖时间',
    campaign_create_date          datetime       null comment '广告活动创建时间',
    campaign_end_date             datetime       null comment '广告活动停止时间',
    ad_group_create_date          datetime       null comment '广告组创建时间',
    ad_group_end_date             datetime       null comment '广告组停止时间',
    etl_data_dt                   datetime       null comment '数据加载日期',
    update_data_dt                datetime       null comment '数据更新日期',
    report_date_str               varchar(10)    null comment '广告报告时间-字符串',
    constraint idx_adv_sku_unique
        unique (report_date, advertising_type, market_place_code, store_id, campaign_id, ad_group_id, goods_code,
                seller_sku)
)
    comment 'sku粒度广告投放表-report_date_str%10==5' charset = utf8;

create table if not exists fenghuo_effect_mkt_adv_sku_06
(
    id                            bigint auto_increment
        primary key,
    profile_id                    varchar(100)   null comment '广告配置id',
    portfolio_id                  varchar(100)   null comment '广告组合id',
    portfolio_name                varchar(100)   null comment '广告组合名称',
    campaign_id                   varchar(100)   null comment '广告活动id',
    campaign_name                 varchar(100)   null comment '广告活动名称',
    ad_group_id                   varchar(100)   null comment '广告组id',
    ad_group_name                 varchar(100)   null comment '广告组名称',
    ad_id                         varchar(100)   null comment '广告id',
    timezone                      varchar(100)   null comment '时区',
    currency_code                 varchar(100)   null comment '货币编码',
    campaign_status               varchar(100)   null comment '广告活动状态',
    ad_group_status               varchar(100)   null comment '广告组状态',
    advertising_type              varchar(100)   null comment '广告类型',
    ad_mode                       varchar(100)   null comment '广告投放模式：自动手动',
    campaign_bidding_strategy     varchar(100)   null comment '竞价策略：固定动态',
    target_keyword                varchar(100)   null comment '关键词还是商品投放',
    bid_plus                      bigint         null comment '竞价溢价',
    campaign_budget_amt           varchar(100)   null comment '广告活动预算金额',
    campaign_budget_type          varchar(100)   null comment '广告活动预算类型',
    campaign_rule_budget_amt      varchar(100)   null comment '广告活动规则基本预算金额',
    campaign_rule_budget_id       varchar(100)   null comment '广告活动规则基本预算id',
    campaign_budget_rule_name     varchar(100)   null comment '广告活动预算规则名称',
    campaign_budget_currency_code varchar(100)   null comment '广告活动预算币种',
    place                         varchar(100)   null comment '广告位',
    sn_code                       varchar(100)   null comment 'sn_code',
    seller_sku                    varchar(100)   null comment '广告推广的子不语sku',
    sku_name                      varchar(100)   null comment 'sku名称',
    asin                          varchar(100)   null comment '推广的Asin',
    parent_asin                   varchar(100)   null comment 'parent_asin',
    item_name                     varchar(300)   null comment 'listing',
    price                         decimal(18, 6) null comment '页面价格',
    goods_code                    varchar(100)   null comment '货号编码',
    goods_id                      bigint         null comment 'goods_id',
    goods_name                    varchar(100)   null comment '货号名称',
    goods_type                    bigint         null comment '商品类型',
    goods_size                    varchar(100)   null comment '商品尺寸',
    goods_color                   varchar(100)   null comment '颜色',
    fit_season_name               varchar(100)   null comment '适销季节',
    category_one_id               varchar(100)   null comment '一级类目id',
    category_one_name             varchar(100)   null comment '一级类目名称',
    category_two_id               varchar(100)   null comment '二级类目id',
    category_two_name             varchar(100)   null comment '二级类目名称',
    category_three_id             varchar(100)   null comment '三级类目id',
    category_three_name           varchar(100)   null comment '三级类目名称',
    category_four_id              varchar(100)   null comment '四级类目id',
    category_four_name            varchar(100)   null comment '四级类目名称',
    category_five_id              varchar(100)   null comment '五级类目id',
    category_five_name            varchar(100)   null comment '五级类目名称',
    category_six_id               varchar(100)   null comment '六级类目id',
    category_six_name             varchar(100)   null comment '六级类目名称',
    store_id                      bigint         null comment '店铺id',
    market_place_code             varchar(100)   null comment '站点编码',
    market_place_name             varchar(100)   null comment '站点',
    platform_id                   varchar(100)   null comment '平台id',
    platform_name                 varchar(100)   null comment '平台名称',
    main_img_url                  varchar(300)   null comment '主图goods_code粒度',
    main_asin_url                 varchar(200)   null comment '主卖链接',
    business_center_id            bigint         null comment '商品事业部id',
    business_center_code          varchar(100)   null comment '商品事业部code',
    business_center_name          varchar(100)   null comment '商品事业部名称',
    first_center_code             varchar(100)   null comment '一级销售事业部编码',
    first_center_name             varchar(100)   null comment '一级销售事业部名称',
    second_center_code            varchar(100)   null comment '二级事业部编码',
    second_center_name            varchar(100)   null comment '二级事业部名称',
    store_name                    varchar(100)   null comment '店铺名名称',
    store_manager                 varchar(100)   null comment '店铺负责人',
    performance_one_id            varchar(100)   null comment '业绩归属人id',
    performance_one_name          varchar(100)   null comment '业绩归属人名称',
    impressions                   bigint         null comment '曝光量',
    clicks                        bigint         null comment '点击量',
    order_quantity                bigint         null comment '归因销售量',
    order_quantity_curr_year      bigint         null comment '当年的总销售量',
    order_quantity_total_year     bigint         null comment '历史累计总销售量',
    order_quantity_7d             bigint         null comment '最近7天销售量',
    order_quantity_1d             bigint         null comment '最近1天的销售量',
    sale_pct                      decimal(18, 6) null comment '售罄率',
    quantity_same_sku             bigint         null comment '本sku的归因广告销售量',
    quantity_same_sku_1d          bigint         null comment '本sku的归因1天广告销售量',
    exchange_rate                 decimal(18, 6) null comment '管理汇率',
    sale_amt                      decimal(18, 6) null comment '总的归因广告销售量',
    sale_amt_1d                   decimal(18, 6) null comment '总的1天归因广告销售量',
    tol_sale_amt                  decimal(18, 6) null comment '总销售金额',
    tol_order_quantity            bigint         null comment '总销售量',
    cost                          decimal(18, 6) null comment '广告花费',
    same_sku_amt                  decimal(18, 6) null comment '本sku归因广告销售金额',
    same_sku_amt_1d               decimal(18, 6) null comment '本sku的1天归因广告销售金额',
    data_dt                       varchar(100)   null comment '数据日期',
    report_date                   datetime       null comment '广告报告时间',
    first_purchase_date           datetime       null comment '首次售卖时间',
    campaign_create_date          datetime       null comment '广告活动创建时间',
    campaign_end_date             datetime       null comment '广告活动停止时间',
    ad_group_create_date          datetime       null comment '广告组创建时间',
    ad_group_end_date             datetime       null comment '广告组停止时间',
    etl_data_dt                   datetime       null comment '数据加载日期',
    update_data_dt                datetime       null comment '数据更新日期',
    report_date_str               varchar(10)    null comment '广告报告时间-字符串',
    constraint idx_adv_sku_unique
        unique (report_date, advertising_type, market_place_code, store_id, campaign_id, ad_group_id, goods_code,
                seller_sku)
)
    comment 'sku粒度广告投放表-report_date_str%10==6' charset = utf8;

create table if not exists fenghuo_effect_mkt_adv_sku_07
(
    id                            bigint auto_increment
        primary key,
    profile_id                    varchar(100)   null comment '广告配置id',
    portfolio_id                  varchar(100)   null comment '广告组合id',
    portfolio_name                varchar(100)   null comment '广告组合名称',
    campaign_id                   varchar(100)   null comment '广告活动id',
    campaign_name                 varchar(100)   null comment '广告活动名称',
    ad_group_id                   varchar(100)   null comment '广告组id',
    ad_group_name                 varchar(100)   null comment '广告组名称',
    ad_id                         varchar(100)   null comment '广告id',
    timezone                      varchar(100)   null comment '时区',
    currency_code                 varchar(100)   null comment '货币编码',
    campaign_status               varchar(100)   null comment '广告活动状态',
    ad_group_status               varchar(100)   null comment '广告组状态',
    advertising_type              varchar(100)   null comment '广告类型',
    ad_mode                       varchar(100)   null comment '广告投放模式：自动手动',
    campaign_bidding_strategy     varchar(100)   null comment '竞价策略：固定动态',
    target_keyword                varchar(100)   null comment '关键词还是商品投放',
    bid_plus                      bigint         null comment '竞价溢价',
    campaign_budget_amt           varchar(100)   null comment '广告活动预算金额',
    campaign_budget_type          varchar(100)   null comment '广告活动预算类型',
    campaign_rule_budget_amt      varchar(100)   null comment '广告活动规则基本预算金额',
    campaign_rule_budget_id       varchar(100)   null comment '广告活动规则基本预算id',
    campaign_budget_rule_name     varchar(100)   null comment '广告活动预算规则名称',
    campaign_budget_currency_code varchar(100)   null comment '广告活动预算币种',
    place                         varchar(100)   null comment '广告位',
    sn_code                       varchar(100)   null comment 'sn_code',
    seller_sku                    varchar(100)   null comment '广告推广的子不语sku',
    sku_name                      varchar(100)   null comment 'sku名称',
    asin                          varchar(100)   null comment '推广的Asin',
    parent_asin                   varchar(100)   null comment 'parent_asin',
    item_name                     varchar(300)   null comment 'listing',
    price                         decimal(18, 6) null comment '页面价格',
    goods_code                    varchar(100)   null comment '货号编码',
    goods_id                      bigint         null comment 'goods_id',
    goods_name                    varchar(100)   null comment '货号名称',
    goods_type                    bigint         null comment '商品类型',
    goods_size                    varchar(100)   null comment '商品尺寸',
    goods_color                   varchar(100)   null comment '颜色',
    fit_season_name               varchar(100)   null comment '适销季节',
    category_one_id               varchar(100)   null comment '一级类目id',
    category_one_name             varchar(100)   null comment '一级类目名称',
    category_two_id               varchar(100)   null comment '二级类目id',
    category_two_name             varchar(100)   null comment '二级类目名称',
    category_three_id             varchar(100)   null comment '三级类目id',
    category_three_name           varchar(100)   null comment '三级类目名称',
    category_four_id              varchar(100)   null comment '四级类目id',
    category_four_name            varchar(100)   null comment '四级类目名称',
    category_five_id              varchar(100)   null comment '五级类目id',
    category_five_name            varchar(100)   null comment '五级类目名称',
    category_six_id               varchar(100)   null comment '六级类目id',
    category_six_name             varchar(100)   null comment '六级类目名称',
    store_id                      bigint         null comment '店铺id',
    market_place_code             varchar(100)   null comment '站点编码',
    market_place_name             varchar(100)   null comment '站点',
    platform_id                   varchar(100)   null comment '平台id',
    platform_name                 varchar(100)   null comment '平台名称',
    main_img_url                  varchar(300)   null comment '主图goods_code粒度',
    main_asin_url                 varchar(200)   null comment '主卖链接',
    business_center_id            bigint         null comment '商品事业部id',
    business_center_code          varchar(100)   null comment '商品事业部code',
    business_center_name          varchar(100)   null comment '商品事业部名称',
    first_center_code             varchar(100)   null comment '一级销售事业部编码',
    first_center_name             varchar(100)   null comment '一级销售事业部名称',
    second_center_code            varchar(100)   null comment '二级事业部编码',
    second_center_name            varchar(100)   null comment '二级事业部名称',
    store_name                    varchar(100)   null comment '店铺名名称',
    store_manager                 varchar(100)   null comment '店铺负责人',
    performance_one_id            varchar(100)   null comment '业绩归属人id',
    performance_one_name          varchar(100)   null comment '业绩归属人名称',
    impressions                   bigint         null comment '曝光量',
    clicks                        bigint         null comment '点击量',
    order_quantity                bigint         null comment '归因销售量',
    order_quantity_curr_year      bigint         null comment '当年的总销售量',
    order_quantity_total_year     bigint         null comment '历史累计总销售量',
    order_quantity_7d             bigint         null comment '最近7天销售量',
    order_quantity_1d             bigint         null comment '最近1天的销售量',
    sale_pct                      decimal(18, 6) null comment '售罄率',
    quantity_same_sku             bigint         null comment '本sku的归因广告销售量',
    quantity_same_sku_1d          bigint         null comment '本sku的归因1天广告销售量',
    exchange_rate                 decimal(18, 6) null comment '管理汇率',
    sale_amt                      decimal(18, 6) null comment '总的归因广告销售量',
    sale_amt_1d                   decimal(18, 6) null comment '总的1天归因广告销售量',
    tol_sale_amt                  decimal(18, 6) null comment '总销售金额',
    tol_order_quantity            bigint         null comment '总销售量',
    cost                          decimal(18, 6) null comment '广告花费',
    same_sku_amt                  decimal(18, 6) null comment '本sku归因广告销售金额',
    same_sku_amt_1d               decimal(18, 6) null comment '本sku的1天归因广告销售金额',
    data_dt                       varchar(100)   null comment '数据日期',
    report_date                   datetime       null comment '广告报告时间',
    first_purchase_date           datetime       null comment '首次售卖时间',
    campaign_create_date          datetime       null comment '广告活动创建时间',
    campaign_end_date             datetime       null comment '广告活动停止时间',
    ad_group_create_date          datetime       null comment '广告组创建时间',
    ad_group_end_date             datetime       null comment '广告组停止时间',
    etl_data_dt                   datetime       null comment '数据加载日期',
    update_data_dt                datetime       null comment '数据更新日期',
    report_date_str               varchar(10)    null comment '广告报告时间-字符串',
    constraint idx_adv_sku_unique
        unique (report_date, advertising_type, market_place_code, store_id, campaign_id, ad_group_id, goods_code,
                seller_sku)
)
    comment 'sku粒度广告投放表-report_date_str%10==7' charset = utf8;

create table if not exists fenghuo_effect_mkt_adv_sku_08
(
    id                            bigint auto_increment
        primary key,
    profile_id                    varchar(100)   null comment '广告配置id',
    portfolio_id                  varchar(100)   null comment '广告组合id',
    portfolio_name                varchar(100)   null comment '广告组合名称',
    campaign_id                   varchar(100)   null comment '广告活动id',
    campaign_name                 varchar(100)   null comment '广告活动名称',
    ad_group_id                   varchar(100)   null comment '广告组id',
    ad_group_name                 varchar(100)   null comment '广告组名称',
    ad_id                         varchar(100)   null comment '广告id',
    timezone                      varchar(100)   null comment '时区',
    currency_code                 varchar(100)   null comment '货币编码',
    campaign_status               varchar(100)   null comment '广告活动状态',
    ad_group_status               varchar(100)   null comment '广告组状态',
    advertising_type              varchar(100)   null comment '广告类型',
    ad_mode                       varchar(100)   null comment '广告投放模式：自动手动',
    campaign_bidding_strategy     varchar(100)   null comment '竞价策略：固定动态',
    target_keyword                varchar(100)   null comment '关键词还是商品投放',
    bid_plus                      bigint         null comment '竞价溢价',
    campaign_budget_amt           varchar(100)   null comment '广告活动预算金额',
    campaign_budget_type          varchar(100)   null comment '广告活动预算类型',
    campaign_rule_budget_amt      varchar(100)   null comment '广告活动规则基本预算金额',
    campaign_rule_budget_id       varchar(100)   null comment '广告活动规则基本预算id',
    campaign_budget_rule_name     varchar(100)   null comment '广告活动预算规则名称',
    campaign_budget_currency_code varchar(100)   null comment '广告活动预算币种',
    place                         varchar(100)   null comment '广告位',
    sn_code                       varchar(100)   null comment 'sn_code',
    seller_sku                    varchar(100)   null comment '广告推广的子不语sku',
    sku_name                      varchar(100)   null comment 'sku名称',
    asin                          varchar(100)   null comment '推广的Asin',
    parent_asin                   varchar(100)   null comment 'parent_asin',
    item_name                     varchar(300)   null comment 'listing',
    price                         decimal(18, 6) null comment '页面价格',
    goods_code                    varchar(100)   null comment '货号编码',
    goods_id                      bigint         null comment 'goods_id',
    goods_name                    varchar(100)   null comment '货号名称',
    goods_type                    bigint         null comment '商品类型',
    goods_size                    varchar(100)   null comment '商品尺寸',
    goods_color                   varchar(100)   null comment '颜色',
    fit_season_name               varchar(100)   null comment '适销季节',
    category_one_id               varchar(100)   null comment '一级类目id',
    category_one_name             varchar(100)   null comment '一级类目名称',
    category_two_id               varchar(100)   null comment '二级类目id',
    category_two_name             varchar(100)   null comment '二级类目名称',
    category_three_id             varchar(100)   null comment '三级类目id',
    category_three_name           varchar(100)   null comment '三级类目名称',
    category_four_id              varchar(100)   null comment '四级类目id',
    category_four_name            varchar(100)   null comment '四级类目名称',
    category_five_id              varchar(100)   null comment '五级类目id',
    category_five_name            varchar(100)   null comment '五级类目名称',
    category_six_id               varchar(100)   null comment '六级类目id',
    category_six_name             varchar(100)   null comment '六级类目名称',
    store_id                      bigint         null comment '店铺id',
    market_place_code             varchar(100)   null comment '站点编码',
    market_place_name             varchar(100)   null comment '站点',
    platform_id                   varchar(100)   null comment '平台id',
    platform_name                 varchar(100)   null comment '平台名称',
    main_img_url                  varchar(300)   null comment '主图goods_code粒度',
    main_asin_url                 varchar(200)   null comment '主卖链接',
    business_center_id            bigint         null comment '商品事业部id',
    business_center_code          varchar(100)   null comment '商品事业部code',
    business_center_name          varchar(100)   null comment '商品事业部名称',
    first_center_code             varchar(100)   null comment '一级销售事业部编码',
    first_center_name             varchar(100)   null comment '一级销售事业部名称',
    second_center_code            varchar(100)   null comment '二级事业部编码',
    second_center_name            varchar(100)   null comment '二级事业部名称',
    store_name                    varchar(100)   null comment '店铺名名称',
    store_manager                 varchar(100)   null comment '店铺负责人',
    performance_one_id            varchar(100)   null comment '业绩归属人id',
    performance_one_name          varchar(100)   null comment '业绩归属人名称',
    impressions                   bigint         null comment '曝光量',
    clicks                        bigint         null comment '点击量',
    order_quantity                bigint         null comment '归因销售量',
    order_quantity_curr_year      bigint         null comment '当年的总销售量',
    order_quantity_total_year     bigint         null comment '历史累计总销售量',
    order_quantity_7d             bigint         null comment '最近7天销售量',
    order_quantity_1d             bigint         null comment '最近1天的销售量',
    sale_pct                      decimal(18, 6) null comment '售罄率',
    quantity_same_sku             bigint         null comment '本sku的归因广告销售量',
    quantity_same_sku_1d          bigint         null comment '本sku的归因1天广告销售量',
    exchange_rate                 decimal(18, 6) null comment '管理汇率',
    sale_amt                      decimal(18, 6) null comment '总的归因广告销售量',
    sale_amt_1d                   decimal(18, 6) null comment '总的1天归因广告销售量',
    tol_sale_amt                  decimal(18, 6) null comment '总销售金额',
    tol_order_quantity            bigint         null comment '总销售量',
    cost                          decimal(18, 6) null comment '广告花费',
    same_sku_amt                  decimal(18, 6) null comment '本sku归因广告销售金额',
    same_sku_amt_1d               decimal(18, 6) null comment '本sku的1天归因广告销售金额',
    data_dt                       varchar(100)   null comment '数据日期',
    report_date                   datetime       null comment '广告报告时间',
    first_purchase_date           datetime       null comment '首次售卖时间',
    campaign_create_date          datetime       null comment '广告活动创建时间',
    campaign_end_date             datetime       null comment '广告活动停止时间',
    ad_group_create_date          datetime       null comment '广告组创建时间',
    ad_group_end_date             datetime       null comment '广告组停止时间',
    etl_data_dt                   datetime       null comment '数据加载日期',
    update_data_dt                datetime       null comment '数据更新日期',
    report_date_str               varchar(10)    null comment '广告报告时间-字符串',
    constraint idx_adv_sku_unique
        unique (report_date, advertising_type, market_place_code, store_id, campaign_id, ad_group_id, goods_code,
                seller_sku)
)
    comment 'sku粒度广告投放表-report_date_str%10==8' charset = utf8;

create table if not exists fenghuo_effect_mkt_adv_sku_09
(
    id                            bigint auto_increment
        primary key,
    profile_id                    varchar(100)   null comment '广告配置id',
    portfolio_id                  varchar(100)   null comment '广告组合id',
    portfolio_name                varchar(100)   null comment '广告组合名称',
    campaign_id                   varchar(100)   null comment '广告活动id',
    campaign_name                 varchar(100)   null comment '广告活动名称',
    ad_group_id                   varchar(100)   null comment '广告组id',
    ad_group_name                 varchar(100)   null comment '广告组名称',
    ad_id                         varchar(100)   null comment '广告id',
    timezone                      varchar(100)   null comment '时区',
    currency_code                 varchar(100)   null comment '货币编码',
    campaign_status               varchar(100)   null comment '广告活动状态',
    ad_group_status               varchar(100)   null comment '广告组状态',
    advertising_type              varchar(100)   null comment '广告类型',
    ad_mode                       varchar(100)   null comment '广告投放模式：自动手动',
    campaign_bidding_strategy     varchar(100)   null comment '竞价策略：固定动态',
    target_keyword                varchar(100)   null comment '关键词还是商品投放',
    bid_plus                      bigint         null comment '竞价溢价',
    campaign_budget_amt           varchar(100)   null comment '广告活动预算金额',
    campaign_budget_type          varchar(100)   null comment '广告活动预算类型',
    campaign_rule_budget_amt      varchar(100)   null comment '广告活动规则基本预算金额',
    campaign_rule_budget_id       varchar(100)   null comment '广告活动规则基本预算id',
    campaign_budget_rule_name     varchar(100)   null comment '广告活动预算规则名称',
    campaign_budget_currency_code varchar(100)   null comment '广告活动预算币种',
    place                         varchar(100)   null comment '广告位',
    sn_code                       varchar(100)   null comment 'sn_code',
    seller_sku                    varchar(100)   null comment '广告推广的子不语sku',
    sku_name                      varchar(100)   null comment 'sku名称',
    asin                          varchar(100)   null comment '推广的Asin',
    parent_asin                   varchar(100)   null comment 'parent_asin',
    item_name                     varchar(300)   null comment 'listing',
    price                         decimal(18, 6) null comment '页面价格',
    goods_code                    varchar(100)   null comment '货号编码',
    goods_id                      bigint         null comment 'goods_id',
    goods_name                    varchar(100)   null comment '货号名称',
    goods_type                    bigint         null comment '商品类型',
    goods_size                    varchar(100)   null comment '商品尺寸',
    goods_color                   varchar(100)   null comment '颜色',
    fit_season_name               varchar(100)   null comment '适销季节',
    category_one_id               varchar(100)   null comment '一级类目id',
    category_one_name             varchar(100)   null comment '一级类目名称',
    category_two_id               varchar(100)   null comment '二级类目id',
    category_two_name             varchar(100)   null comment '二级类目名称',
    category_three_id             varchar(100)   null comment '三级类目id',
    category_three_name           varchar(100)   null comment '三级类目名称',
    category_four_id              varchar(100)   null comment '四级类目id',
    category_four_name            varchar(100)   null comment '四级类目名称',
    category_five_id              varchar(100)   null comment '五级类目id',
    category_five_name            varchar(100)   null comment '五级类目名称',
    category_six_id               varchar(100)   null comment '六级类目id',
    category_six_name             varchar(100)   null comment '六级类目名称',
    store_id                      bigint         null comment '店铺id',
    market_place_code             varchar(100)   null comment '站点编码',
    market_place_name             varchar(100)   null comment '站点',
    platform_id                   varchar(100)   null comment '平台id',
    platform_name                 varchar(100)   null comment '平台名称',
    main_img_url                  varchar(300)   null comment '主图goods_code粒度',
    main_asin_url                 varchar(200)   null comment '主卖链接',
    business_center_id            bigint         null comment '商品事业部id',
    business_center_code          varchar(100)   null comment '商品事业部code',
    business_center_name          varchar(100)   null comment '商品事业部名称',
    first_center_code             varchar(100)   null comment '一级销售事业部编码',
    first_center_name             varchar(100)   null comment '一级销售事业部名称',
    second_center_code            varchar(100)   null comment '二级事业部编码',
    second_center_name            varchar(100)   null comment '二级事业部名称',
    store_name                    varchar(100)   null comment '店铺名名称',
    store_manager                 varchar(100)   null comment '店铺负责人',
    performance_one_id            varchar(100)   null comment '业绩归属人id',
    performance_one_name          varchar(100)   null comment '业绩归属人名称',
    impressions                   bigint         null comment '曝光量',
    clicks                        bigint         null comment '点击量',
    order_quantity                bigint         null comment '归因销售量',
    order_quantity_curr_year      bigint         null comment '当年的总销售量',
    order_quantity_total_year     bigint         null comment '历史累计总销售量',
    order_quantity_7d             bigint         null comment '最近7天销售量',
    order_quantity_1d             bigint         null comment '最近1天的销售量',
    sale_pct                      decimal(18, 6) null comment '售罄率',
    quantity_same_sku             bigint         null comment '本sku的归因广告销售量',
    quantity_same_sku_1d          bigint         null comment '本sku的归因1天广告销售量',
    exchange_rate                 decimal(18, 6) null comment '管理汇率',
    sale_amt                      decimal(18, 6) null comment '总的归因广告销售量',
    sale_amt_1d                   decimal(18, 6) null comment '总的1天归因广告销售量',
    tol_sale_amt                  decimal(18, 6) null comment '总销售金额',
    tol_order_quantity            bigint         null comment '总销售量',
    cost                          decimal(18, 6) null comment '广告花费',
    same_sku_amt                  decimal(18, 6) null comment '本sku归因广告销售金额',
    same_sku_amt_1d               decimal(18, 6) null comment '本sku的1天归因广告销售金额',
    data_dt                       varchar(100)   null comment '数据日期',
    report_date                   datetime       null comment '广告报告时间',
    first_purchase_date           datetime       null comment '首次售卖时间',
    campaign_create_date          datetime       null comment '广告活动创建时间',
    campaign_end_date             datetime       null comment '广告活动停止时间',
    ad_group_create_date          datetime       null comment '广告组创建时间',
    ad_group_end_date             datetime       null comment '广告组停止时间',
    etl_data_dt                   datetime       null comment '数据加载日期',
    update_data_dt                datetime       null comment '数据更新日期',
    report_date_str               varchar(10)    null comment '广告报告时间-字符串',
    constraint idx_adv_sku_unique
        unique (report_date, advertising_type, market_place_code, store_id, campaign_id, ad_group_id, goods_code,
                seller_sku)
)
    comment 'sku粒度广告投放表-report_date_str%10==9' charset = utf8;

create table if not exists fenghuo_effect_product_targeting_keyword
(
    id                        bigint auto_increment
        primary key,
    user_name                 varchar(100)   null,
    user_id                   varchar(100)   null,
    platform_name             varchar(100)   null,
    platform_id               varchar(100)   null,
    market_place_name         varchar(100)   null,
    market_place_code         varchar(100)   null,
    first_center_name         varchar(100)   null,
    first_center_code         varchar(100)   null,
    second_center_name        varchar(100)   null,
    second_center_code        varchar(100)   null,
    store_manager             varchar(100)   null,
    store_name                varchar(100)   null,
    store_id                  bigint         null,
    timezone                  varchar(100)   null,
    advertising_type          varchar(100)   null,
    ad_mode                   varchar(100)   null,
    campaign_bidding_strategy varchar(100)   null,
    portfolio_id              varchar(100)   null,
    portfolio_name            varchar(100)   null,
    campaign_name             varchar(100)   null,
    campaign_id               varchar(100)   null,
    campaign_status           varchar(100)   null,
    currency_code             varchar(100)   null,
    campaign_create_date      datetime       null,
    campaign_end_date         datetime       null,
    ad_group_name             varchar(100)   null,
    ad_group_id               varchar(100)   null,
    ad_group_create_date      datetime       null,
    ad_group_end_date         datetime       null,
    ad_group_status           varchar(100)   null,
    target_keyword            varchar(100)   null,
    match_type                varchar(100)   null,
    impressions               bigint         null,
    clicks                    bigint         null,
    order_quantiy             bigint         null,
    sale_amt                  decimal(18, 6) null,
    cost                      decimal(18, 6) null,
    cpc                       decimal(18, 6) null,
    acos                      decimal(18, 6) null,
    roas                      decimal(18, 6) null,
    ctr                       decimal(18, 6) null,
    cvr                       decimal(18, 6) null,
    target_cnt                bigint         null,
    place_is                  decimal(18, 6) null,
    data_dt                   varchar(100)   null,
    etl_data_dt               datetime       null,
    update_data_dt            datetime       null,
    target_id                 varchar(100)   null,
    targeting                 varchar(100)   null,
    ad_keyword_status         varchar(100)   null,
    targeting_text            varchar(100)   null,
    targeting_type            varchar(100)   null,
    targeting_expression      varchar(100)   null,
    target_status             varchar(100)   null,
    constraint idx_target_keyword_unique
        unique (store_id, target_keyword, target_id, campaign_id, ad_group_id)
)
    comment '投放品和关键词效果';

create table if not exists fenghuo_effect_sku
(
    id                        bigint auto_increment
        primary key,
    user_name                 varchar(64)    null comment '租户名称',
    user_id                   varchar(64)    null comment '租户id',
    platform_name             varchar(64)    null comment '平台名称',
    platform_id               varchar(64)    null comment '平台id',
    market_place_name         varchar(64)    null comment '站点',
    market_place_code         varchar(64)    null comment '站点编码',
    first_center_name         varchar(64)    null comment '销售一级事业部名称',
    first_center_code         varchar(64)    null comment '销售一级事业部编码',
    second_center_name        varchar(64)    null comment '销售二级事业部名称',
    second_center_code        varchar(64)    null comment '销售二级事业部编码',
    store_manager             varchar(64)    null comment '店铺负责人',
    store_name                varchar(64)    null comment '店铺名称',
    store_id                  varchar(64)    null comment '店铺id',
    bc_id                     varchar(64)    null comment 'bc_id',
    timezone                  varchar(64)    null comment '时区',
    advertising_type          varchar(64)    null comment '广告类型',
    ad_mode                   varchar(64)    null comment '广告模式',
    campaign_bidding_strategy varchar(64)    null comment '广告活动竞价策略',
    portfolio_id              varchar(64)    null comment '广告组合id',
    portfolio_name            varchar(64)    null comment '广告组合名称',
    campaign_name             varchar(200)   null comment '广告活动名称',
    campaign_id               varchar(64)    null comment '广告活动id',
    campaign_status           varchar(64)    null comment '广告活动最新状态',
    currency_code             varchar(64)    null comment '币种',
    campaign_create_date      datetime       null comment '广告活动创建时间',
    campaign_end_date         datetime       null comment '广告活动结束时间',
    ad_group_name             varchar(64)    null comment '广告组名称',
    ad_group_id               varchar(64)    null comment '广告组id',
    ad_group_create_date      varchar(64)    null comment '广告组创建时间',
    ad_group_end_date         varchar(64)    null comment '广告组结束时间',
    ad_group_status           varchar(64)    null comment '广告组状态',
    category_one_name         varchar(64)    null comment '一级类目',
    category_one_id           varchar(64)    null,
    category_two_name         varchar(64)    null comment '二级类目',
    category_two_id           varchar(64)    null,
    category_three_name       varchar(64)    null comment '三级类目',
    category_three_id         varchar(64)    null,
    category_four_name        varchar(64)    null comment '四级类目',
    category_four_id          varchar(64)    null,
    category_five_name        varchar(64)    null comment '五级类目',
    category_five_id          varchar(64)    null,
    category_six_name         varchar(64)    null comment '六级类目',
    category_six_id           varchar(64)    null,
    goods_name                varchar(64)    null comment '货号名称',
    goods_code                varchar(64)    null comment '货号',
    item_name                 varchar(300)   null comment 'listing',
    main_img_url              varchar(64)    null comment '主图链接',
    main_asin_url             varchar(64)    null comment '主卖链接',
    price                     varchar(64)    null comment '页面价格',
    parent_asin               varchar(64)    null comment '父asin',
    asin                      varchar(64)    null comment '子asin',
    sku_name                  varchar(64)    null comment '尺码色号',
    seller_sku                varchar(64)    null comment '推广的sku',
    impressions               bigint         null comment '曝光量',
    clicks                    bigint         null comment '点击量',
    order_quantiy             bigint         null comment '广告销售量',
    sale_amt                  decimal(18, 6) null comment '广告销售额',
    cost                      decimal(18, 6) null comment '广告花费',
    cpc                       decimal(18, 6) null comment '单个点击成本',
    acos                      decimal(18, 6) null comment '成本收入占比',
    roas                      decimal(18, 6) null comment '投入产出比',
    ctr                       decimal(18, 6) null comment '点击率',
    cvr                       decimal(18, 6) null comment '转化率',
    target_cnt                bigint         null comment '定位总数',
    tacos                     decimal(18, 6) null comment 'tacos',
    qty_pct                   decimal(18, 6) null comment '广告销售量占比(本SKU)',
    amt_pct                   decimal(18, 6) null comment '广告销售额占比(本SKU)',
    data_dt                   varchar(64)    null,
    etl_data_dt               varchar(64)    null,
    update_data_dt            varchar(64)    null,
    constraint idx_sku_unique
        unique (market_place_code, store_id, advertising_type, campaign_id, ad_group_id, seller_sku)
)
    comment '广告sku累计统计表' charset = utf8;

create table if not exists fenghuo_keyword
(
    id                      bigint                               not null
        primary key,
    profile_id              varchar(64)                          not null comment '关联的市场店铺Id',
    keyword_id              varchar(64)                          null comment '关键字ID',
    keyword_text            varchar(256)                         null comment '关键字',
    match_type              varchar(64)                          null comment '匹配类型',
    ad_group_id             varchar(64)                          null comment '关联的市场店铺Id',
    campaign_id             varchar(64)                          null comment '亚马逊Id',
    state                   varchar(32)                          null comment 'The state of the campaign. e.g.,enabled, paused, archived',
    bid                     decimal(20, 4)                       null,
    serving_status          varchar(64)                          null comment 'The status of the campaign.e.g.,[ ADVERTISER_STATUS_ENABLED, STATUS_UNAVAILABLE, ADVERTISER_PAUSED, ACCOUNT_OUT_OF_BUDGET, ADVERTISER_PAYMENT_FAILURE, CAMPAIGN_PAUSED, CAMPAIGN_ARCHIVED, PENDING_START_DATE, ENDED, CAMPAIGN_OUT_OF_BUDGET ]',
    native_language_keyword varchar(256)                         null,
    creation_date           bigint                               null comment 'Epoch date the campaign was created.',
    last_updated_date       bigint                               null comment 'Epoch date of the last update to any property associated with the campaign in Amazon',
    creator                 varchar(20)                          null,
    modifier                varchar(20)                          null,
    deleted                 tinyint(1) default 0                 null,
    enabled                 tinyint(1) default 1                 null,
    gmt_create              datetime   default CURRENT_TIMESTAMP not null comment '创建时间',
    gmt_modified            datetime   default CURRENT_TIMESTAMP not null on update CURRENT_TIMESTAMP comment '修改时间',
    constraint uk_keyword_id
        unique (keyword_id)
)
    comment '关键字';

create index idx_key1
    on fenghuo_keyword (ad_group_id);

create index idx_key2
    on fenghuo_keyword (profile_id, ad_group_id);

create index idx_key3
    on fenghuo_keyword (campaign_id);

create table if not exists fenghuo_neg_keyword
(
    id                bigint                               not null
        primary key,
    profile_id        varchar(64)                          not null comment '关联的市场店铺Id',
    keyword_id        varchar(64)                          null comment '关键字ID',
    keyword_text      varchar(256)                         null comment '关键字',
    match_type        varchar(64)                          null comment '匹配类型',
    ad_group_id       varchar(64)                          null comment '关联的市场店铺Id',
    campaign_id       varchar(64)                          null comment '亚马逊Id',
    state             varchar(32)                          null comment 'The state of the campaign. e.g.,enabled, paused, archived',
    serving_status    varchar(64)                          null comment 'The status of the campaign.e.g.,[ ADVERTISER_STATUS_ENABLED, STATUS_UNAVAILABLE, ADVERTISER_PAUSED, ACCOUNT_OUT_OF_BUDGET, ADVERTISER_PAYMENT_FAILURE, CAMPAIGN_PAUSED, CAMPAIGN_ARCHIVED, PENDING_START_DATE, ENDED, CAMPAIGN_OUT_OF_BUDGET ]',
    creation_date     bigint                               null comment 'Epoch date the campaign was created.',
    last_updated_date bigint                               null comment 'Epoch date of the last update to any property associated with the campaign in Amazon',
    creator           varchar(20)                          null,
    modifier          varchar(20)                          null,
    deleted           tinyint(1) default 0                 null,
    enabled           tinyint(1) default 1                 null,
    gmt_create        datetime   default CURRENT_TIMESTAMP not null comment '创建时间',
    gmt_modified      datetime   default CURRENT_TIMESTAMP not null on update CURRENT_TIMESTAMP comment '修改时间',
    constraint uk_keyword_id
        unique (keyword_id)
)
    comment '否定关键字';

create index idx_key1
    on fenghuo_neg_keyword (ad_group_id);

create index idx_key2
    on fenghuo_neg_keyword (profile_id, ad_group_id);

create index idx_key3
    on fenghuo_neg_keyword (campaign_id);

create table if not exists fenghuo_neg_product_targeting
(
    id                  bigint                               not null
        primary key,
    profile_id          varchar(64)                          not null comment '关联的市场店铺Id',
    target_id           varchar(64)                          null comment '投放品ID',
    ad_group_id         varchar(64)                          null comment '关联的市场店铺Id',
    campaign_id         varchar(64)                          null comment '亚马逊Id',
    expression_type     varchar(64)                          null comment 'The type of expression',
    expression          json                                 null comment 'The targeting expression.',
    resolved_expression json                                 null comment 'The resolved targeting expression.',
    state               varchar(32)                          null comment 'The state of the campaign. e.g.,enabled, paused, archived',
    serving_status      varchar(64)                          null comment 'The status of the campaign.e.g.,[ ADVERTISER_STATUS_ENABLED, STATUS_UNAVAILABLE, ADVERTISER_PAUSED, ACCOUNT_OUT_OF_BUDGET, ADVERTISER_PAYMENT_FAILURE, CAMPAIGN_PAUSED, CAMPAIGN_ARCHIVED, PENDING_START_DATE, ENDED, CAMPAIGN_OUT_OF_BUDGET ]',
    creation_date       bigint                               null comment 'Epoch date the campaign was created.',
    last_updated_date   bigint                               null comment 'Epoch date of the last update to any property associated with the campaign in Amazon',
    creator             varchar(20)                          null,
    modifier            varchar(20)                          null,
    deleted             tinyint(1) default 0                 null,
    enabled             tinyint(1) default 1                 null,
    gmt_create          datetime   default CURRENT_TIMESTAMP not null comment '创建时间',
    gmt_modified        datetime   default CURRENT_TIMESTAMP not null on update CURRENT_TIMESTAMP comment '修改时间',
    constraint uk_target_id
        unique (target_id)
)
    comment '否投放品';

create index idx_key1
    on fenghuo_neg_product_targeting (ad_group_id);

create index idx_key2
    on fenghuo_neg_product_targeting (profile_id, ad_group_id);

create index idx_key3
    on fenghuo_neg_product_targeting (campaign_id);

create table if not exists fenghuo_odps_recommend_asin
(
    id                  bigint auto_increment
        primary key,
    parent_asin         varchar(64)  null,
    asin                varchar(64)  null,
    category_one_name   varchar(64)  null,
    category_one_id     varchar(64)  null,
    category_two_name   varchar(64)  null,
    category_two_id     varchar(64)  null,
    category_three_name varchar(64)  null,
    category_three_id   varchar(64)  null,
    category_four_name  varchar(64)  null,
    category_four_id    varchar(64)  null,
    category_five_name  varchar(64)  null,
    category_five_id    varchar(64)  null,
    category_six_name   varchar(64)  null,
    category_six_id     varchar(64)  null,
    cat_key             varchar(300) null,
    cat_level           bigint       null,
    data_dt             varchar(64)  null,
    etl_data_dt         datetime     null,
    update_data_dt      datetime     null,
    cat_id              varchar(100) null,
    constraint cat_id
        unique (cat_id, parent_asin, asin),
    constraint idx_asin
        unique (asin)
)
    comment '数仓推荐关键词-asin表' charset = utf8;

create table if not exists fenghuo_odps_recommend_asin2
(
    id                  bigint default 0         not null,
    parent_asin         varchar(64) charset utf8 null,
    asin                varchar(64) charset utf8 not null
        primary key,
    category_one_name   varchar(64) charset utf8 null,
    category_one_id     varchar(64) charset utf8 null,
    category_two_name   varchar(64) charset utf8 null,
    category_two_id     varchar(64) charset utf8 null,
    category_three_name varchar(64) charset utf8 null,
    category_three_id   varchar(64) charset utf8 null,
    category_four_name  varchar(64) charset utf8 null,
    category_four_id    varchar(64) charset utf8 null,
    category_five_name  varchar(64) charset utf8 null,
    category_five_id    varchar(64) charset utf8 null,
    category_six_name   varchar(64) charset utf8 null,
    category_six_id     varchar(64) charset utf8 null,
    cat_key             varchar(64) charset utf8 null,
    cat_level           bigint                   null,
    data_dt             varchar(64) charset utf8 null,
    etl_data_dt         datetime                 null,
    update_data_dt      datetime                 null,
    constraint parent_asin
        unique (parent_asin, asin)
);

create table if not exists fenghuo_odps_recommend_asin3
(
    id                  bigint default 0         not null,
    parent_asin         varchar(64) charset utf8 null,
    asin                varchar(64) charset utf8 not null,
    category_one_name   varchar(64) charset utf8 null,
    category_one_id     varchar(64) charset utf8 null,
    category_two_name   varchar(64) charset utf8 null,
    category_two_id     varchar(64) charset utf8 null,
    category_three_name varchar(64) charset utf8 null,
    category_three_id   varchar(64) charset utf8 null,
    category_four_name  varchar(64) charset utf8 null,
    category_four_id    varchar(64) charset utf8 null,
    category_five_name  varchar(64) charset utf8 null,
    category_five_id    varchar(64) charset utf8 null,
    category_six_name   varchar(64) charset utf8 null,
    category_six_id     varchar(64) charset utf8 null,
    cat_key             varchar(64) charset utf8 null,
    cat_id              varchar(64) charset utf8 null,
    cat_level           bigint                   null,
    data_dt             varchar(64) charset utf8 null,
    etl_data_dt         datetime                 null,
    update_data_dt      datetime                 null
);

create table if not exists fenghuo_odps_recommend_asin_keywords
(
    id                  bigint auto_increment
        primary key,
    category_one_name   varchar(64)    null,
    category_two_name   varchar(64)    null,
    category_three_name varchar(64)    null,
    category_four_name  varchar(64)    null,
    category_five_name  varchar(64)    null,
    category_six_name   varchar(64)    null,
    cat_key             varchar(300)   null,
    cat_level           varchar(64)    null,
    parent_asin         varchar(64)    null,
    asin                varchar(64)    null,
    campaign_status     varchar(64)    null comment '最新的广告活动状态',
    keyword_text        varchar(300)   null comment '投放关键词',
    impressions         bigint         null comment '曝光量',
    clicks              bigint         null comment '点击量',
    cost                decimal(18, 6) null comment '花费',
    order_quantity      bigint         null comment '广告销售量',
    sale_amt            decimal(18, 6) null comment '广告销售额',
    ctr                 decimal(18, 6) null comment '点击转化率',
    cvr                 decimal(18, 6) null comment '销售转化率',
    cat_id              varchar(100)   null,
    market_place_code   varchar(64)    null,
    market_place_name   varchar(64)    null,
    constraint market_place_code
        unique (market_place_code, cat_id, parent_asin, asin, keyword_text),
    constraint market_place_name
        unique (market_place_name, cat_id, parent_asin, asin, keyword_text)
)
    comment '数仓推荐关键词-keyword表' charset = utf8;

create table if not exists fenghuo_odps_recommend_asin_keywords2
(
    id                  bigint default 0         not null,
    category_one_name   varchar(64) charset utf8 null,
    category_two_name   varchar(64) charset utf8 null,
    category_three_name varchar(64) charset utf8 null,
    category_four_name  varchar(64) charset utf8 null,
    category_five_name  varchar(64) charset utf8 null,
    category_six_name   varchar(64) charset utf8 null,
    cat_key             varchar(64) charset utf8 null,
    cat_level           varchar(64) charset utf8 null,
    parent_asin         varchar(64) charset utf8 null,
    asin                varchar(64) charset utf8 null,
    campaign_status     varchar(64) charset utf8 null comment '最新的广告活动状态',
    keyword_text        varchar(64) charset utf8 null comment '投放关键词',
    impressions         bigint                   null comment '曝光量',
    clicks              bigint                   null comment '点击量',
    cost                decimal(18, 6)           null comment '花费',
    order_quantity      bigint                   null comment '广告销售量',
    sale_amt            decimal(18, 6)           null comment '广告销售额',
    ctr                 decimal(18, 6)           null comment '点击转化率',
    cvr                 decimal(18, 6)           null comment '销售转化率',
    constraint parent_asin
        unique (parent_asin, asin, keyword_text)
);

create table if not exists fenghuo_odps_recommend_asin_keywords3
(
    id                  bigint auto_increment
        primary key,
    category_one_name   varchar(64)    null,
    category_two_name   varchar(64)    null,
    category_three_name varchar(64)    null,
    category_four_name  varchar(64)    null,
    category_five_name  varchar(64)    null,
    category_six_name   varchar(64)    null,
    cat_key             varchar(64)    null,
    cat_id              varchar(64)    null,
    cat_level           varchar(64)    null,
    parent_asin         varchar(64)    null,
    asin                varchar(64)    null,
    campaign_status     varchar(64)    null comment '最新的广告活动状态',
    keyword_text        varchar(64)    null comment '投放关键词',
    impressions         bigint         null comment '曝光量',
    clicks              bigint         null comment '点击量',
    cost                decimal(18, 6) null comment '花费',
    order_quantity      bigint         null comment '广告销售量',
    sale_amt            decimal(18, 6) null comment '广告销售额',
    ctr                 decimal(18, 6) null comment '点击转化率',
    cvr                 decimal(18, 6) null comment '销售转化率'
)
    comment '数仓推荐关键词-keyword表' charset = utf8;

create table if not exists fenghuo_portfolios
(
    id                bigint                               not null
        primary key,
    profile_id        varchar(64)                          not null comment '关联的市场店铺Id',
    portfolio_id      varchar(64)                          null comment '广告组合ID',
    name              varchar(64)                          null comment '名称',
    in_budget         int(20)                              null comment 'boolean Indicates the current budget status of the portfolio. Set to true if the portfolio is in budget, set to false if the portfolio is out of budget.',
    budget            json                                 null comment 'The targeting expression.',
    state             varchar(32)                          null comment 'The state of the campaign. e.g.,enabled, paused, archived',
    serving_status    varchar(64)                          null comment 'The status of the campaign.e.g.,[ ADVERTISER_STATUS_ENABLED, STATUS_UNAVAILABLE, ADVERTISER_PAUSED, ACCOUNT_OUT_OF_BUDGET, ADVERTISER_PAYMENT_FAILURE, CAMPAIGN_PAUSED, CAMPAIGN_ARCHIVED, PENDING_START_DATE, ENDED, CAMPAIGN_OUT_OF_BUDGET ]',
    creation_date     bigint                               null comment 'Epoch date the campaign was created.',
    last_updated_date bigint                               null comment 'Epoch date of the last update to any property associated with the campaign in Amazon',
    creator           varchar(20)                          null,
    modifier          varchar(20)                          null,
    deleted           tinyint(1) default 0                 null,
    enabled           tinyint(1) default 1                 null,
    gmt_create        datetime   default CURRENT_TIMESTAMP not null comment '创建时间',
    gmt_modified      datetime   default CURRENT_TIMESTAMP not null on update CURRENT_TIMESTAMP comment '修改时间',
    constraint uk_portfolio_id
        unique (portfolio_id)
)
    comment '广告组合';

create index idx_key1
    on fenghuo_portfolios (profile_id, portfolio_id);

create table if not exists fenghuo_product_ad
(
    id                bigint                               not null
        primary key,
    profile_id        varchar(64)                          not null comment '关联的市场店铺Id',
    ad_id             varchar(64)                          null comment '推广品ID',
    ad_group_id       varchar(64)                          null comment '关联的市场店铺Id',
    campaign_id       varchar(64)                          null comment '亚马逊Id',
    sku               varchar(128)                         null comment 'sku',
    asin              varchar(128)                         null comment 'asin',
    state             varchar(32)                          null comment 'The state of the campaign. e.g.,enabled, paused, archived',
    serving_status    varchar(64)                          null comment 'The status of the campaign.e.g.,[ ADVERTISER_STATUS_ENABLED, STATUS_UNAVAILABLE, ADVERTISER_PAUSED, ACCOUNT_OUT_OF_BUDGET, ADVERTISER_PAYMENT_FAILURE, CAMPAIGN_PAUSED, CAMPAIGN_ARCHIVED, PENDING_START_DATE, ENDED, CAMPAIGN_OUT_OF_BUDGET ]',
    creation_date     bigint                               null comment 'Epoch date the campaign was created.',
    last_updated_date bigint                               null comment 'Epoch date of the last update to any property associated with the campaign in Amazon',
    creator           varchar(20)                          null,
    modifier          varchar(20)                          null,
    deleted           tinyint(1) default 0                 null,
    enabled           tinyint(1) default 1                 null,
    gmt_create        datetime   default CURRENT_TIMESTAMP not null comment '创建时间',
    gmt_modified      datetime   default CURRENT_TIMESTAMP not null on update CURRENT_TIMESTAMP comment '修改时间',
    constraint uk_ad_id
        unique (ad_id)
)
    comment '推广品';

create index idx_key1
    on fenghuo_product_ad (ad_group_id, asin);

create index idx_key2
    on fenghuo_product_ad (profile_id, asin);

create index idx_key3
    on fenghuo_product_ad (campaign_id);

create table if not exists fenghuo_product_targeting
(
    id                  bigint                               not null
        primary key,
    profile_id          varchar(64)                          not null comment '关联的市场店铺Id',
    target_id           varchar(64)                          null comment '投放品ID',
    ad_group_id         varchar(64)                          null comment '关联的市场店铺Id',
    campaign_id         varchar(64)                          null comment '亚马逊Id',
    expression_type     varchar(64)                          null comment 'The type of expression',
    bid                 decimal(20, 4)                       null comment 'The bid for ads sourced using the target. Targets that do not have bid values in listTargetingClauses will inherit the defaultBid from the adGroup level.',
    expression          json                                 null comment 'The targeting expression.',
    resolved_expression json                                 null comment 'The resolved targeting expression.',
    state               varchar(32)                          null comment 'The state of the campaign. e.g.,enabled, paused, archived',
    serving_status      varchar(64)                          null comment 'The status of the campaign.e.g.,[ ADVERTISER_STATUS_ENABLED, STATUS_UNAVAILABLE, ADVERTISER_PAUSED, ACCOUNT_OUT_OF_BUDGET, ADVERTISER_PAYMENT_FAILURE, CAMPAIGN_PAUSED, CAMPAIGN_ARCHIVED, PENDING_START_DATE, ENDED, CAMPAIGN_OUT_OF_BUDGET ]',
    creation_date       bigint                               null comment 'Epoch date the campaign was created.',
    last_updated_date   bigint                               null comment 'Epoch date of the last update to any property associated with the campaign in Amazon',
    creator             varchar(20)                          null,
    modifier            varchar(20)                          null,
    deleted             tinyint(1) default 0                 null,
    enabled             tinyint(1) default 1                 null,
    gmt_create          datetime   default CURRENT_TIMESTAMP not null comment '创建时间',
    gmt_modified        datetime   default CURRENT_TIMESTAMP not null on update CURRENT_TIMESTAMP comment '修改时间',
    constraint uk_target_id
        unique (target_id)
)
    comment '投放品';

create index idx_key1
    on fenghuo_product_targeting (ad_group_id);

create index idx_key2
    on fenghuo_product_targeting (profile_id, ad_group_id);

create index idx_key3
    on fenghuo_product_targeting (campaign_id);

create table if not exists fenghuo_seller_shopuser
(
    id            bigint               not null
        primary key,
    gmt_create    datetime(3)          null,
    gmt_modified  datetime(3)          null,
    creator       varchar(20)          null,
    modifier      varchar(20)          null,
    deleted       tinyint(1) default 0 null,
    enabled       tinyint(1) default 1 null,
    employee_no   bigint               null comment 'USC系统中的人员no',
    shop_id       bigint               null comment 'siteshop的主键Id',
    role          varchar(10)          null comment '角色，enum: manager,user',
    shop_erp_id   varchar(20)          null comment '店铺erp系统中的Id',
    employee_name varchar(10)          null comment 'USC系统中的人员名称'
)
    comment '店铺使用人信息' charset = utf8;

create index idx_shop_user
    on fenghuo_seller_shopuser (shop_id, employee_no);

create index idx_user_shop
    on fenghuo_seller_shopuser (employee_no, shop_id, role);

create table if not exists fenghuo_seller_siteshop
(
    id                    bigint               not null
        primary key,
    gmt_create            datetime(3)          not null,
    gmt_modified          datetime(3)          null,
    creator               varchar(20)          null,
    modifier              varchar(20)          null,
    deleted               tinyint(1) default 0 null,
    enabled               tinyint(1) default 1 null,
    name                  varchar(40)          null comment '店铺名称',
    erp_id                varchar(20)          null comment 'Erp系统中的Id',
    amazon_id             varchar(18)          null comment '亚马逊系统中的Id',
    marketplace_string_id varchar(32)          null comment '在亚马逊系统中的The identifier of the marketplace to which the account is associated.',
    profile_id            varchar(20)          null comment '广告关联的Id',
    country_code          varchar(3)           null,
    currency_code         varchar(4)           null comment 'The currency used for all monetary values for entities under this profile.',
    timezone              varchar(20)          null comment 'The time zone used for all date-based campaign management and reporting.',
    tenant_id             varchar(20)          null comment '租户Id'
)
    comment '烽火系统中亚马逊的店铺信息' charset = utf8;

create table if not exists sync_metadata_job
(
    id               bigint                                  not null
        primary key,
    gmt_create       datetime      default CURRENT_TIMESTAMP not null comment '创建时间',
    gmt_modified     datetime      default CURRENT_TIMESTAMP not null on update CURRENT_TIMESTAMP comment '修改时间',
    creator          varchar(20)                             null,
    profile_id       varchar(32)                             not null comment '亚马逊profileId',
    available_status tinyint(2)    default 0                 not null comment '可以运行的任务：1 是，2 false',
    job_type         int(1)        default 1                 not null comment '任务类型，1: 同步一个profileId下的各种信息',
    job_status       int           default 2                 not null comment '任务状态：1 未开始 2 排队中  3 进行中 4 暂停 5 完成  6 等待终止 7 终止 8 失败',
    ip               varchar(32)   default ''                not null comment 'ip',
    last_finish_time bigint                                  null comment '上次完成时间',
    run_num          int           default 0                 not null comment '运行次数',
    version          int           default 0                 not null comment '版本号',
    progress         varchar(32)                             null,
    error_reason     varchar(2048) default ''                not null,
    remark           varchar(256)  default ''                not null,
    env              varchar(32)   default 'local'           not null comment '区分环境拉取',
    endpoint_url     varchar(64)   default ''                not null comment '调用亚马逊API endpoint',
    constraint uk_profileId_jobtype
        unique (profile_id, job_type)
)
    comment '同步信息任务表' charset = utf8;

create index idx_available_status_job_status_job_type
    on sync_metadata_job (available_status, job_status, job_type);

